#!/usr/bin/env bash
# The script transfer a file from our client to a server
#  scp -i ~/.ssh/holberton README.md ubuntu@34.75.120.130:~/

if [ $# -lt 3 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# echo "scp -i $4 $1 $3@$2:~/ -o StrictHostKeyChecking=no"
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi