#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.6 -y
sudo apt-get update
sudo apt-get install haproxy=1.6.\* -y

sudo echo "
frontend Local_Server
bind *:80
mode http
default_backend web_backend
backend web_backend
balance roundrobin
server 1294-web-01 34.75.120.130:80 check
server 1294-web-02 35.185.98.157:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo echo ENABLED=1 | sudo tee /etc/default/haproxy
sudo service haproxy restart