#!/usr/bin/env bash
# you must do everything that you can to prevent an attacker from logging in as root.

pkill -9 apache2
chown -R nginx /etc/nginx /var/log/nginx /usr/share/nginx
chmod 740 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
chown nginx /run/nginx.pid
su nginx -c nginx
